#!/usr/bin/env bash
# One-click setup of the Goose agent harness on Linux/macOS, pointed at the GB10
# model server. Installs the Goose CLI, writes config.yaml (vLLM primary + Ollama
# fallback), verifies connectivity, and runs a tool-calling smoke test.
#
# Mirrors HarnessAgent/docs/install_results.md. Safe to re-run.
#
# Usage:
#   ./setup_goose.sh                         # vLLM backend, default GB10 host
#   GB10_HOST=192.168.86.44 BACKEND=ollama ./setup_goose.sh
#   BACKEND=vllm GOOSE_VERSION=v1.39.0 SKIP_SMOKE=1 ./setup_goose.sh
set -euo pipefail

GB10_HOST="${GB10_HOST:-192.168.86.44}"
BACKEND="${BACKEND:-vllm}"            # vllm | ollama
GOOSE_VERSION="${GOOSE_VERSION:-stable}"
SKIP_SMOKE="${SKIP_SMOKE:-0}"

VLLM_BASE="http://${GB10_HOST}:8000"
OLLAMA_BASE="http://${GB10_HOST}:11434"

c_info(){ printf '\033[36m[*]\033[0m %s\n' "$*"; }
c_ok(){   printf '\033[32m[OK]\033[0m %s\n' "$*"; }
c_warn(){ printf '\033[33m[!]\033[0m %s\n' "$*"; }
c_die(){  printf '\033[31m[X]\033[0m %s\n' "$*"; exit 1; }

echo "=== Goose harness setup ($(uname -s) -> GB10 ${GB10_HOST}, backend=${BACKEND}) ==="

command -v curl >/dev/null 2>&1 || c_die "curl is required."

# --- 1. Connectivity (non-fatal) ---
backend_up=0
if [ "$BACKEND" = "vllm" ]; then
  c_info "Checking vLLM at ${VLLM_BASE}/v1/models ..."
  if curl -sf --max-time 8 "${VLLM_BASE}/v1/models" >/dev/null; then c_ok "vLLM reachable"; backend_up=1
  else c_warn "vLLM unreachable; will still install + write config."; fi
else
  c_info "Checking Ollama at ${OLLAMA_BASE}/api/tags ..."
  if curl -sf --max-time 8 "${OLLAMA_BASE}/api/tags" >/dev/null; then c_ok "Ollama reachable"; backend_up=1
  else c_warn "Ollama unreachable; will still install + write config."; fi
fi

# --- 2. Install Goose CLI (official installer, no interactive configure) ---
c_info "Installing Goose CLI ($GOOSE_VERSION) ..."
INSTALL_URL="https://github.com/aaif-goose/goose/releases/download/${GOOSE_VERSION}/download_cli.sh"
curl -fsSL "$INSTALL_URL" | CONFIGURE=false bash

# Locate goose binary
GOOSE_BIN=""
for cand in "$HOME/.local/bin/goose" "$(command -v goose 2>/dev/null || true)"; do
  if [ -n "$cand" ] && [ -x "$cand" ]; then GOOSE_BIN="$cand"; break; fi
done
[ -n "$GOOSE_BIN" ] || c_die "goose binary not found after install (expected ~/.local/bin/goose)."
case ":$PATH:" in *":$HOME/.local/bin:"*) ;; *) export PATH="$HOME/.local/bin:$PATH";
  c_warn "Add 'export PATH=\$HOME/.local/bin:\$PATH' to your shell profile for future sessions." ;; esac
c_ok "Installed: $("$GOOSE_BIN" --version | tr '\n' ' ')  ($GOOSE_BIN)"

# --- 3. Write config.yaml (~/.config/goose/config.yaml) ---
CFG_DIR="$HOME/.config/goose"
mkdir -p "$CFG_DIR"
CFG="$CFG_DIR/config.yaml"

if [ "$BACKEND" = "vllm" ]; then
  read -r -d '' PROV <<EOF || true
GOOSE_PROVIDER: openai
GOOSE_MODEL: qwen-3.6-chat
OPENAI_HOST: ${VLLM_BASE}
OPENAI_BASE_PATH: v1/chat/completions
OPENAI_API_KEY: sk-local
# Fallback (uncomment to use Ollama):
# GOOSE_PROVIDER: ollama
# GOOSE_MODEL: qwen3.5:9b
OLLAMA_HOST: ${OLLAMA_BASE}
OLLAMA_TIMEOUT: 900
GOOSE_STREAM_TIMEOUT: 900
OLLAMA_STREAM_TIMEOUT: 900
EOF
else
  read -r -d '' PROV <<EOF || true
GOOSE_PROVIDER: ollama
GOOSE_MODEL: qwen3.5:9b
OLLAMA_HOST: ${OLLAMA_BASE}
OLLAMA_TIMEOUT: 900
GOOSE_STREAM_TIMEOUT: 900
OLLAMA_STREAM_TIMEOUT: 900
# Fallback (uncomment to use vLLM):
# GOOSE_PROVIDER: openai
# GOOSE_MODEL: qwen-3.6-chat
# OPENAI_HOST: ${VLLM_BASE}
# OPENAI_BASE_PATH: v1/chat/completions
# OPENAI_API_KEY: sk-local
EOF
fi

cat > "$CFG" <<EOF
# Goose CLI configuration - generated by HarnessAgent/setup_goose.sh
# Goose runs on this machine; models served on GB10 (${GB10_HOST}).
# vLLM requires GB10 launched with --enable-auto-tool-choice --tool-call-parser qwen3_coder
# (see HarnessAgent/config/docker-compose.yaml). Ollama needs no GB10 flags.

${PROV}

# Privacy: disable goose's usage telemetry. goose otherwise POSTs usage metadata
# (model, extensions, session names, token/session counts, settings) to a hosted
# PostHog endpoint (us.i.posthog.com). Keep this false so no data leaves this
# machine without approval. Your prompts/responses always stay on your provider
# (here the local vLLM/Ollama). See docs/install_results.md "Telemetry / privacy".
GOOSE_TELEMETRY_ENABLED: false

extensions:
  developer:
    type: builtin
    bundled: true
    name: developer
    enabled: true
    timeout: 300
  memory:
    type: stdio
    bundled: false
    name: memory
    enabled: true
    cmd: ${GOOSE_BIN}
    args:
      - mcp
      - memory
    env_keys: []
    timeout: 300
    description: Example stdio MCP extension (goose bundled 'memory' server)
EOF
c_ok "Wrote config -> $CFG (active backend: $BACKEND)"

# --- 4. Smoke test ---
if [ "$SKIP_SMOKE" = "1" ]; then
  c_warn "Smoke test skipped (SKIP_SMOKE=1)."
elif [ "$backend_up" != "1" ]; then
  c_warn "Backend unreachable; skipping smoke test. Re-run once GB10 is up."
else
  c_info "Smoke test: headless tool-calling (may take ~10s-2min)..."
  WORK="$(mktemp -d)"; ( cd "$WORK" && GOOSE_MODE=auto GOOSE_TELEMETRY_ENABLED=false "$GOOSE_BIN" run --no-session --max-turns 6 \
      -t "Create ./ok.txt containing the word READY, then stop." || true )
  if [ -f "$WORK/ok.txt" ]; then c_ok "Smoke test PASSED -> $(tr -d '\n' < "$WORK/ok.txt")"
  else c_warn "Smoke test did NOT create the file. Check backend/tool-calling."; fi
  rm -rf "$WORK"
fi

echo
c_ok "Done. Use it with:  GOOSE_MODE=auto goose run --no-session -t \"your task\""
echo "    Interactive: goose session"
