# profiles_helpers.ps1 -- agent-profile helpers shared by server.ps1 (folded into $DiscoveryFns like
# mcp_toggle.ps1) and the sandboxed test. Path-parameterized: no live-path constants here.
# Depends on Set-ExtensionEnabled (mcp_toggle.ps1) being in scope for Invoke-ProfileApply.

function Get-AgentProfiles($path) {
    if (-not (Test-Path -LiteralPath $path)) { throw "profiles.json not found: $path" }
    $arr = @((Get-Content -Raw -LiteralPath $path -Encoding UTF8 | ConvertFrom-Json))
    $seen = @{}
    foreach ($p in $arr) {
        foreach ($f in 'name', 'label', 'description', 'recipe') {
            if (-not $p.$f) { throw "profiles.json: entry missing '$f'" }
        }
        if (-not $p.enable -or @($p.enable).Count -eq 0) { throw "profile '$($p.name)': empty enable list" }
        if ($seen.ContainsKey($p.name)) { throw "profiles.json: duplicate name '$($p.name)'" }
        $seen[$p.name] = $true
    }
    return $arr
}

function Get-ManagedExtIds($profiles) {
    $ids = @{}
    foreach ($p in $profiles) { foreach ($i in $p.enable) { $ids[[string]$i] = $true } }
    return @($ids.Keys)
}

function Get-ConfigExtIds($configPath) {
    # The extension ids actually present in the config's `extensions:` block (indent-2 keys).
    # Used to skip managed ids that don't exist in this config instead of trying to set them.
    $ids = @{}
    if (-not (Test-Path -LiteralPath $configPath)) { return $ids }
    $inExt = $false
    foreach ($raw in (Get-Content -LiteralPath $configPath -Encoding UTF8)) {
        $s = ([string]$raw).Trim()
        if ($s -eq '' -or $s.StartsWith('#')) { continue }
        $indent = ([string]$raw).Length - ([string]$raw).TrimStart(' ').Length
        if ($indent -eq 0) { $inExt = ($s -eq 'extensions:'); continue }
        if ($inExt -and $indent -eq 2 -and $s -match '^([A-Za-z0-9_.\-]+):\s*$') { $ids[$Matches[1]] = $true }
    }
    return $ids
}

function Get-ActiveProfileName($profiles, $extStates) {
    # $extStates: hashtable id -> [bool]enabled (only managed ids are compared)
    $managed = Get-ManagedExtIds $profiles
    $enabledManaged = @($managed | Where-Object { $extStates.ContainsKey($_) -and $extStates[$_] }) | Sort-Object
    foreach ($p in $profiles) {
        $want = @($p.enable | Sort-Object)
        if (($enabledManaged -join "`n") -eq ($want -join "`n")) { return [string]$p.name }
    }
    return 'custom'
}

function Invoke-ProfileApply($profilesPath, $configPath, $workspaceDir, $repoRoot, $name) {
    # validate EVERYTHING before any write
    $profiles = Get-AgentProfiles $profilesPath
    $prof = $profiles | Where-Object { $_.name -eq $name } | Select-Object -First 1
    if ($null -eq $prof) { throw "unknown profile: $name" }
    $recipePath = Join-Path $repoRoot ([string]$prof.recipe -replace '/', '\')
    if (-not (Test-Path -LiteralPath $recipePath)) { throw "recipe not found: $($prof.recipe)" }
    $recipe = Get-Content -Raw -LiteralPath $recipePath -Encoding UTF8
    if (-not (Test-Path -LiteralPath $configPath)) { throw "goose config not found: $configPath" }

    Copy-Item -LiteralPath $configPath -Destination "$configPath.bak-profile" -Force

    $enable = @{}; foreach ($i in $prof.enable) { $enable[[string]$i] = $true }
    $present = Get-ConfigExtIds $configPath
    $changed = @(); $skipped = @(); $warnings = @()
    foreach ($id in (Get-ManagedExtIds $profiles)) {
        # ignore managed ids that don't exist in this config -- don't try to set them
        if (-not $present.ContainsKey($id)) { $skipped += $id; continue }
        $want = $enable.ContainsKey($id)
        try {
            if (Set-ExtensionEnabled $configPath $id $want) { $changed += $id }
        } catch {
            $warnings += "skip ${id}: $_"     # unexpected write failure -- not fatal
        }
    }

    try {
        $header = "# profile: $name -- generated by goose_web /api/profiles; do not edit (reapply the profile instead)"
        $utf8 = New-Object System.Text.UTF8Encoding($false)
        [System.IO.File]::WriteAllText((Join-Path $workspaceDir '.goosehints'),
                                       ($header + "`n`n" + $recipe), $utf8)
    } catch {
        $warnings += "goosehints write failed: $_"
    }
    return @{ ok = $true; name = [string]$name; changed = $changed; skipped = $skipped; warnings = $warnings }
}
